@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@apiVersion = v1.0

###
GET http://{{host}}/api/{{apiVersion}}/ping HTTP/1.1

### Components endpoints
@components = components

### Get all Components
GET http://{{host}}/api/{{apiVersion}}/{{components}}/all HTTP/1.1

### Get a Component
GET http://{{host}}/api/{{apiVersion}}/{{components}}/CMPR99 HTTP/1.1

### Create a test Component
POST http://{{host}}/api/{{apiVersion}}/{{components}}/new HTTP/1.1
Content-Type: {{contentType}}

{
  "_id": "CMPR99",
  "name": "Componente de prueba",
  "teacher": "teacher",
  "students": ["student1", "student2"]
}

### Update a test Component
PUT http://{{host}}/api/{{apiVersion}}/{{components}}/CMPR99 HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Componente de prueba editado",
  "teacher": "fhperez"
}

### Delete a test Component
DELETE http://{{host}}/api/{{apiVersion}}/{{components}}/CMPR99 HTTP/1.1

### Delete all Components
DELETE http://{{host}}/api/{{apiVersion}}/{{components}}/all HTTP/1.1

### URL Error
GET http://{{host}}/api/{{apiVersion}}/{{components}}/urlerror HTTP/1.1

### Data for StudentOwl-Monitoreo
### Create a GTPR01 Component
POST http://{{host}}/api/{{apiVersion}}/{{components}}/new HTTP/1.1
Content-Type: {{contentType}}

{
  "_id": "GTPR01",
  "name": "Gestión de proyectos",
  "teacher": "mpabad",
  "students": ["jjgahona", "lfbermeo", "jjramirez8", "vhmartinez5"]
}

### Create a INRE01 Component
POST http://{{host}}/api/{{apiVersion}}/{{components}}/new HTTP/1.1
Content-Type: {{contentType}}

{
  "_id": "INRE01",
  "name": "Ingeniería de requisitos",
  "teacher": "racorrea2",
  "students": []
}

### Get all students from a component
GET http://{{host}}/api/{{apiVersion}}/students/GTPR01 HTTP/1.1